### PR TITLE
Split Draw in two traits and make their resource parameters

### PR DESCRIPTION
**Pull request by tomaka**
Makes it possible to have multiple different images and text styles implemented on the same drawer.

### CODE REVIEW

**Comment by elliegoldstein** [comment]
Question: is this project maintained / will this be merged? (I know it's a project that seems to be mostly finished and a PR that's quite old, but I was interested in adding immi support and this would be helpful.)

**Comment by tomaka** [comment]
Heh, thanks for the ping!
Yes this project is old and "finished" and not really maintained, but as far as I remember this PR was supposed to be merged and I simply forgot about it.

**Comment by elliegoldstein** [comment]
No problem, just didn't want to be a bother. I assume this will require a `2.x` release?

**Comment by tomaka** [comment]
Yes, that's a pretty big breaking change.

**Pull request merged**
